/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./script/GameMgr"
import UIPingmushipei_Pos from "./script/UIPingmushipei_Pos"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=960;
    static height:number=640;
    static scaleMode:string="fixedheight";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="startScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameMgr.ts",GameMgr);
        reg("script/UIPingmushipei_Pos.ts",UIPingmushipei_Pos);
    }
}
GameConfig.init();